### ISSUE TITLE
Why installing sat-search installs the older version of sat-stac?

### ISSUE THREAD

**Issue by bidhya** [sat-utils/sat-search#100]
Even though 0.4 version of sat-stac is available on both conda-forge and pip, somehow the sat-search installs sat-stac 0.3.3. This behaviour happened on both windows and Linux machines. I was trying to follow the example notebooks, and there were multiple errors due to this older version of sat-stac.

**Comment by matthewhanson** [comment]
Hi @bidhya ,
Which version of sat-search are you installing? The previous versions of sat-search (0.2.3 and earlier) are pegged to an older version of sat-stac.

The sat-search `develop` branch has the latest version, which is 0.3.0-rc1.  I've got some changes to make to get a final release out this week for that, which will use sat-stac 0.4.0

**Comment by bidhya** [comment]
Yes, I am using 0.2.3 that came with conda-forge. I will try develop branch now, and wait for the final release.

**Comment by bidhya** [comment]
Resolved with new update to sat-search this week
