### ISSUE TITLE
Is there a difference between sat-search and satsearch?

### ISSUE THREAD

**Issue by bidhya** [sat-utils/sat-search#101]
This github says install this package using: pip install sat-search
On conda-forge it say: conda install -c conda-forge satsearch

Is there are difference between the two. Or should I prefer one over the other?

**Comment by matthewhanson** [comment]
There's no difference, the maintainer for the conda package just removed the dash.

sat-search is the Python package name so that's how you install it:
$ pip install sat-search

but when you import it in Python dashes aren't allowed, so just:

import satsearch

**Comment by bidhya** [comment]
Thank you
