### ISSUE TITLE
Sorting doesn't work

### ISSUE THREAD

**Issue by NiklasJordan** [sat-utils/sat-search#117]
I'm building a simple search with sat-search. Everything is working right, but the sorting doesn't. I have no idea why. In your examples it is the same way.

Here is my code and the results:
![Screenshot 2021-04-09 at 14 02 44](https://user-images.githubusercontent.com/715033/114177099-4afb4200-993c-11eb-8a94-f0ff1520aed4.png)

**Comment by mwip** [comment]
I also was trying a dictionary-based search. What you are looking for is 

```
Search(
    ...
    sortby = '-properties.eo:cloud_cover', 
)
```

ref https://github.com/sat-utils/sat-search/issues/90#issuecomment-680142347

**Comment by NiklasJordan** [comment]
> ```
> Search(
>     ...
>     sortby = '-properties.eo:cloud_cover', 
> )
> ```

Thats works perfectly. Thanks!

**Comment by NiklasJordan** [comment]
How can I change the sort direction?

**Comment by mwip** [comment]
by changing the sign:  `'-properties.eo:cloud_cover'` to `'+properties.eo:cloud_cover'` (or ommitting it altogether)

**Comment by NiklasJordan** [comment]
@mwip Thanks a lot. That helps.
