### ISSUE TITLE
Notebook tutorial no longer works

### ISSUE THREAD

**Issue by giswqs** [sat-utils/sat-search#130]
It seems the [notebook tutorial](https://github.com/sat-utils/sat-search/blob/master/tutorial-1.ipynb) no longer works. All searches return 0 items. 

![image](https://user-images.githubusercontent.com/5016453/187582629-89d058a3-1b3a-4553-bf9c-c1b3fec68b88.png)

**Comment by matthewhanson** [comment]
Hello @giswqs .  The sat-search library is no longer maintained, however there is a new library called pystac-client which works in a very similar way:
https://github.com/stac-utils/pystac-client

Check out the notebook tutorials in the docs/ directory.

**Comment by giswqs** [comment]
Thanks. I will look into it.
