### ISSUE TITLE
Incorrect Sentinel-2 file keys

### ISSUE THREAD

**Issue by NosyParker** [sat-utils/sat-search#31]
Hello!
I 've played with this great lib and have noticed that downloading keys for sentinel-2 are incorrect:
if entering B01,B02, etc keys in readme, then it'll just return number of found scenes, but if entering keys without "B" (01, 02, etc) it works great;

![image](https://user-images.githubusercontent.com/14200611/38822387-bdbdd5e4-41bc-11e8-9cee-0de027ca0794.png)

**Comment by matthewhanson** [comment]
@NosyParker There is a new version of sat-search that is more explicit regarding the keys to download as it uses a new version of sat-api, see:
https://sat-api.developmentseed.org/search/stac
