### ISSUE TITLE
STAC compliance: using POST (plus headers)

### ISSUE THREAD

**Issue by adsnash** [sat-utils/sat-search#54]
I really like the work you've done here with sat-search. However, to be officially STAC compliant (per the documentation), "The POST endpoint is required for all STAC API implementations" source: https://github.com/radiantearth/stac-spec/tree/master/api-spec

I've poked around the repo a bit, and I don't think it would be particularly difficult to implement POST as well as header support and more command line options. If this is something you'd be interested in, I'd be happy to work on it in my free time (and know at least one other guy who would as well).

**Comment by matthewhanson** [comment]
Hi @adsnash sorry I've let this go and not responded.  We're currently working on the new version of sat-search that will work with sat-api 0.2.0 and it will include POST support. Look for that to get released (at least a release candidate version) by the end of the year.

**Comment by adsnash** [comment]
Awesome! I'll be looking forward to that release. In that case, I'll close this issue
