### ISSUE TITLE
no satsearch in pipy or anaconda 

### ISSUE THREAD

**Issue by dorbodwolf** [sat-utils/sat-search#57]
> It is recommended to use pyenv and virtualenv to to control Python versions and installed dependencies. sat-search can be conveniently installed from PyPi:
> 

> ```
> # install the latest release version
> $ pip install satsearch
> ```

> 

`$ pip install satsearch`
```
Collecting satsearch
  Could not find a version that satisfies the requirement satsearch (from versions: )
No matching distribution found for satsearch
```

**Comment by dorbodwolf** [comment]
Thanks for yours amazing jobs that is great help to all us. But I cannot find detailed documentations of sat-search with STAC, can I contribute in writing docs and tutorials, that will be my pleasure！

**Comment by matthewhanson** [comment]
@dorbodwolf Hi, thanks for the offer. Docs, tutorials, or any other PR is always welcome!

Right now we're working on a new version of sat-search and I will the docs some, but anything you want to provide would be great.

**Comment by matthewhanson** [comment]
Hello @dorbodwolf ,

We've released a new version of sat-search (along with sat-api and our deployed API at sat-api.developmentseed.org), which has updated to use sat-api 0.2.3 and follows the STAC spec.

Querying now works differently, as it follows the STAC spec. See the documentation at:
http://sat-utils.github.io/sat-api/

I've added some additional documentation. The README has info on installing and usage of the CLI, while the new Jupyter notebook is a tutorial on using it as a Python library.

I'm going to close this issue but please feel free to open any new ones as needed!
