### ISSUE TITLE
changing reposetory

### ISSUE THREAD

**Issue by ziya5635** [sat-utils/sat-search#73]
Hi, I wonder it is possible to change the repository from for example Sentinel hub to another hub that supports Sentinel (like Finhub)? If so, could you please tell me where I should modify? Thank you.

**Comment by matthewhanson** [comment]
Hello @ziya5635 , I'm not sure what you mean here. I think you are referring to https://sat-api.developmentseed.org/stac which is the default endpoint for sat-search. That index does not include Sentinel data from Sentinel Hub, but instead is an index of the Sentinel-2 data on AWS:
https://registry.opendata.aws/sentinel-2/

All sat-search is doing is searching a STAC API, so whatever dataset that API has indexed is what you get back.
