### ISSUE TITLE
spatial resolution of sentinel2 B8A

### ISSUE THREAD

**Issue by samsammurphy** [sat-utils/sat-search#81]
Sentinel2 waveband 8A _should_ have a [spatial resolution of 20 m](https://earth.esa.int/web/sentinel/user-guides/sentinel-2-msi/resolutions/spatial).

When I download a scene using `sat-search load` it seems to have a spatial resolution of 10 m (?) e.g. S2A_10SGF_20190616_0.

Is this the right place to report this?

**Comment by samsammurphy** [comment]
This is related to the following issue https://github.com/sat-utils/sat-stac/issues/42

**Comment by matthewhanson** [comment]
Thanks @samsammurph for filing this issue!   The proper place for Sentinel related issues is https://github.com/sat-utils/sat-stac-sentinel

I will be updating the Sentinel-2 catalog (and adding a Sentinel-1 catalog) over the course of July so will make sure to fix these issues!

**Comment by samsammurphy** [comment]
Thanks @matthewhanson 

Looks like this issue was already raised

https://github.com/sat-utils/sat-stac-sentinel/issues/11
