### ISSUE TITLE
Seperate valid scenes from invalid?

### ISSUE THREAD

**Issue by AtlasHale** [sat-utils/sat-search#89]
This isn't exactly an issue, more of a question. I have a set of long/lat points which I want to extract satellite images of, so I am trying to download the RGB bands and combine them. However, some of the scenes returned have images which are not usable, and it is unclear what causes this behavior. An example of this is when running the following code
```
search = Search(bbox=[-120.671912, 38, -121.566920, 40],
               datetime='2018-10-30/2018-11-07',
               property=["eo:cloud_cover < 100"])
print('bbox search: %s items' % search.found())
items = search.items()
print(type(items))
items.save('test.json')
# items.download('B4')
# items.download('B3')
# items.download('B2')
items.download('thumbnail')
```
Some of the downloaded thumbnails are what I would expect, for example 
![image](https://user-images.githubusercontent.com/37227138/66781580-87a1c680-ee88-11e9-9550-c59ae1ca4d0f.png)
However others are like so:
![image](https://user-images.githubusercontent.com/37227138/66781606-94261f00-ee88-11e9-9fae-e2d1981a597a.png)

Is there a way to filter out these kinds of results?

**Comment by matthewhanson** [comment]
Hi @AtlasHale, can you provide an ID of a couple of the scenes that look bad?  Based on the orientation of the image it looks like this might be a nighttime scene (when the platform is in an ascending orbit).   They should not have been indexed in sat-api, but there might be something wrong with the ingest.

**Comment by AtlasHale** [comment]
Some ID's are:
LC81392112018290LGN00
LC81392112018306LGN00
LC81392122018290LGN00
LC81392122018306LGN00
LC81402112018297LGN00

I found these with search parameters
```
search = Search(bbox=[-120.671912, 39.2, -120.8, 39.8],
               datetime='2018-10-15/2018-11-07',
               property=["eo:cloud_cover < 100"])
```
There are 6 valid Landsat results, and 5 of the distorted results in the search.items()

**Comment by matthewhanson** [comment]
This is more of an issue with the DevSeed deployment of sat-api, if it's still an issue it should be filed there:
https://github.com/sat-utils/sat-api/issues
