### ISSUE TITLE
Update references to SATUTILS_API_URL in readme & tutorial

### ISSUE THREAD

**Issue by dylnclrk** [sat-utils/sat-search#98]
I noticed the tutorial and readme need to be updated with the new env var name.

 `SATUTILS_API_URL` => `STAC_API_URL`

---------------

Also, I think the tutorial has the incorrect default URL:
> Sat-search uses an endpoint defined by the SATUTILS_API_URL environment variable. This defaults to https://sat-api.developmentseed.org/ but can point to any STAC compatible endpoint."

I think it should say:
>  Sat-search uses an endpoint defined by the **_STAC_API_URL_** environment variable. This defaults to **_https://1tqdbvsut9.execute-api.us-west-2.amazonaws.com/v0_** but can point to any STAC compatible endpoint."

**Comment by matthewhanson** [comment]
Thanks for pointing this out @dylnclrk , I've updated those references and made some other fixes to the README and tutorial.
